# Generated by Django 6.1.1 on 2026-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kitproducto',
            name='kit_producto_unico',
        ),
        migrations.AddField(
            model_name='kit',
            name='tipo_producto',
            field=models.CharField(choices=[('SENSORIAL', 'Sensorial'), ('DECORACION', 'Decoración'), ('JUGUETE', 'Juguete'), ('OTRO', 'Otro')], default='SENSORIAL', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KitProducto',
        ),
    ]
