# Generated by Django 6.1.1 on 2026-09-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0002_remove_kitproducto_kit_producto_unico_and_more'),
        ('productos', '0004_tipoproducto_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='productos.tipoproducto'),
        ),
    ]
