# Generated by Django 6.1.1 on 2026-09-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0003_alter_kit_tipo_producto'),
        ('productos', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='kit',
            name='modalidad',
            field=models.CharField(choices=[('LIBRE_CATEGORIA', 'Libre por categoría'), ('FIJO', 'Composición fija')], default='LIBRE_CATEGORIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='kit',
            name='cantidad_productos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kit',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='productos.tipoproducto'),
        ),
        migrations.CreateModel(
            name='KitComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='kits.kit')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_fijos', to='productos.producto')),
            ],
            options={
                'ordering': ['producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'producto'), name='kit_producto_fijo_unico')],
            },
        ),
    ]
