# Generated by Django 6.1.1 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricasConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activas",
                    models.BooleanField(
                        default=True,
                        verbose_name="Métricas del catálogo activas",
                    ),
                ),
                (
                    "retencion_dias",
                    models.PositiveSmallIntegerField(
                        default=180,
                        verbose_name="Retención de métricas en días",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de métricas",
                "verbose_name_plural": "Configuración de métricas",
            },
        ),
        migrations.CreateModel(
            name="EventoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Vista"),
                            ("ADD_TO_CART", "Agregar al carrito"),
                            ("CHECKOUT_START", "Inicio de checkout"),
                            ("SOLICITUD", "Solicitud enviada"),
                            ("WHATSAPP", "Click en WhatsApp"),
                            ("INSTAGRAM", "Click en Instagram"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "visitor_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "pagina",
                    models.CharField(
                        blank=True,
                        max_length=40,
                    ),
                ),
                (
                    "contenido_tipo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                    ),
                ),
                (
                    "contenido_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "dispositivo",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Móvil"),
                            ("TABLET", "Tablet"),
                            ("DESKTOP", "Escritorio"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        blank=True,
                        default="Directo",
                        max_length=120,
                    ),
                ),
                (
                    "ruta",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "creada_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-creada_en", "-id"],
                "indexes": [
                    models.Index(
                        fields=["evento", "creada_en"],
                        name="metr_evento_fecha_idx",
                    ),
                    models.Index(
                        fields=[
                            "contenido_tipo",
                            "contenido_id",
                            "creada_en",
                        ],
                        name="metr_contenido_fecha_idx",
                    ),
                    models.Index(
                        fields=["session_hash", "creada_en"],
                        name="metr_sesion_fecha_idx",
                    ),
                ],
            },
        ),
    ]
