# Generated by Django 6.1.1 on 2026-09-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoImpresionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('IMPRIMIENDO', 'Imprimiendo'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_impresion', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pedido', 'producto'), name='estado_impresion_pedido_producto_unico')],
            },
        ),
    ]
