# Generated by Django 6.1.1 on 2026-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_estadoimpresionpedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoimpresionpedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='estadoimpresionpedido',
            name='cantidad_stock_descontada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadoimpresionpedido',
            name='listo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadoimpresionpedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
