# Generated by Django 6.1.1 on 2026-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_estadoimpresionpedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='color_personalizacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_total_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='tipo_item',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('KIT', 'Kit'), ('PERSONALIZADO', 'Personalizado')], max_length=20),
        ),
    ]
