# Generated by Django 6.1.1 on 2026-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
