# Generated by Django 6.1.1 on 2026-09-14 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_detallepedido_costo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('tipo', models.CharField(choices=[('OPERATIVO', 'Gasto operativo'), ('INVERSION', 'Inversión')], default='OPERATIVO', max_length=20)),
                ('categoria', models.CharField(choices=[('FILAMENTO', 'Filamento'), ('INSUMOS', 'Otros insumos'), ('EQUIPAMIENTO', 'Equipamiento'), ('MANTENIMIENTO', 'Mantenimiento'), ('EMBALAJE', 'Embalaje'), ('PUBLICIDAD', 'Publicidad'), ('SERVICIOS', 'Servicios'), ('ENVIO', 'Envíos'), ('SOFTWARE', 'Software'), ('COMISIONES', 'Comisiones'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Débito'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=30)),
                ('cantidad_cuotas', models.PositiveSmallIntegerField(default=1)),
                ('fecha_primera_cuota', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuotaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='pedidos.gasto')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('gasto', 'numero'), name='cuota_gasto_numero_unico')],
            },
        ),
    ]
