# Generated by Django 6.1.1 on 2026-09-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_gasto_cuotagasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('saldo_real', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cuotagasto',
            name='pagada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
