# Generated by Django 6.1.1 on 2026-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración general', max_length=100)),
                ('precio_kg_filamento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('consumo_impresora_w', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amortizacion_por_hora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasa_fallos', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje, por ejemplo 8 para 8%', max_digits=6)),
                ('fecha_desde', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
