# Generated by Django 6.1.1 on 2026-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncostos',
            name='amortizacion_por_hora',
        ),
        migrations.RemoveField(
            model_name='configuracioncostos',
            name='consumo_impresora_w',
        ),
        migrations.RemoveField(
            model_name='configuracioncostos',
            name='costo_kwh',
        ),
        migrations.RemoveField(
            model_name='configuracioncostos',
            name='precio_kg_filamento',
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='coste_amortizacion_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coste amortización por hora'),
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='coste_luz_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coste luz por hora'),
        ),
        migrations.AddField(
            model_name='configuracioncostos',
            name='coste_plastico_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coste plástico por kg'),
        ),
        migrations.AlterField(
            model_name='configuracioncostos',
            name='tasa_fallos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tasa de fallos (%)'),
        ),
    ]
