"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""
import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


BASE_DIR = Path(__file__).resolve().parent.parent


def _env_list(nombre, default=""):
    return [
        valor.strip()
        for valor in os.getenv(nombre, default).split(",")
        if valor.strip()
    ]


def _env_bool(nombre, default=False):
    valor_default = "true" if default else "false"
    return os.getenv(nombre, valor_default).strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


# ----------------------------------------------------------
# SEGURIDAD / ENTORNO
# ----------------------------------------------------------

# Railway expone esta variable automáticamente. La usamos para distinguir
# producción/QA de un runserver local sin obligar a crear un .env.
IS_RAILWAY = bool(os.getenv("RAILWAY_ENVIRONMENT", "").strip())

# APP_ENV permite forzar el entorno de forma explícita. En Railway, si no se
# define, usamos el nombre real del environment (por ejemplo: qa/production).
APP_ENV = (
    os.getenv("APP_ENV", "").strip().lower()
    or os.getenv("RAILWAY_ENVIRONMENT_NAME", "").strip().lower()
    or ("railway" if IS_RAILWAY else "local")
)
IS_QA = APP_ENV in {"qa", "test", "testing", "staging"}

# Local: DEBUG=True por defecto.
# Railway: DEBUG=False por defecto.
# En ambos casos se puede sobrescribir explícitamente con DEBUG.
DEBUG = _env_bool("DEBUG", not IS_RAILWAY)

SECRET_KEY = os.getenv("SECRET_KEY", "").strip()

# En desarrollo local y tests permitimos una clave temporal para no obligar
# a configurar variables. En Railway la clave debe existir explícitamente.
if not SECRET_KEY:
    if IS_RAILWAY:
        raise ImproperlyConfigured(
            "Falta configurar SECRET_KEY en las variables del entorno de Railway."
        )

    SECRET_KEY = "django-insecure-dev-only-no-usar-en-produccion"

ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS",
    "*" if DEBUG and not IS_RAILWAY else "localhost,127.0.0.1,[::1],testserver",
)

railway_public_domain = os.getenv(
    "RAILWAY_PUBLIC_DOMAIN",
    "",
).strip()

if railway_public_domain and railway_public_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_public_domain)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "costos",
    "productos",
    "kits",
    "clientes",
    "pedidos",
    "stock",
    "produccion",
    "dashboard",
    "calculadora",
    "auditoria.apps.AuditoriaConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditoria.middleware.AuditoriaRequestMiddleware",
    "config.auth_middleware.LoginRequiredMiddleware",
    "config.catalog_maintenance_middleware.CatalogMaintenanceMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "config.impresiones_landscape_middleware.ImpresionesLandscapeMiddleware",
    "config.dashboard_refinements_middleware.DashboardRefinementsMiddleware",
    "config.production_experience_middleware.ProductionExperienceMiddleware",
    "config.responsive_fixes_middleware.ResponsiveFixesMiddleware",
    "config.catalog_grid_middleware.CatalogGridMiddleware",
    "config.catalog_contact_middleware.CatalogContactMiddleware",
    "config.catalog_rotator_middleware.CatalogRotatorMiddleware",
    "config.product_images_ui_middleware.ProductImagesUIMiddleware",
    "config.operaciones_ui_middleware.OperacionesUIMiddleware",
    "config.impresiones_mensajes_middleware.MensajesImpresionesMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.ui_middleware.NormalizarNavegacionMiddleware",
    "config.kit_volume_ui_middleware.KitVolumeUIMiddleware",
    "config.pedido_form_lookfeel_middleware.PedidoFormLookFeelMiddleware",
    "config.pedido_form_ui_middleware.PedidoFormUIMiddleware",
    "config.environment_ui_middleware.EnvironmentVisualMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.webpush",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Autenticación

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard:inicio"
LOGOUT_REDIRECT_URL = "login"

# La sesión expira luego de 12 horas y se renueva con actividad.
SESSION_COOKIE_AGE = 60 * 60 * 12
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Protección opcional del checkout público. Si las claves quedan vacías,
# el resto de defensas anti-spam sigue funcionando sin mostrar captcha.
TURNSTILE_SITE_KEY = os.getenv("TURNSTILE_SITE_KEY", "").strip()
TURNSTILE_SECRET_KEY = os.getenv("TURNSTILE_SECRET_KEY", "").strip()

# Interruptor de emergencia del catálogo público. En producción puede dejarse
# activo durante un despliegue grande y apagarse luego sin tocar la base.
CATALOGO_MANTENIMIENTO = _env_bool(
    "CATALOGO_MANTENIMIENTO",
    False,
)

# Web Push para avisos internos (por ejemplo, un nuevo pedido web).
WEBPUSH_VAPID_PUBLIC_KEY = os.getenv(
    "WEBPUSH_VAPID_PUBLIC_KEY",
    "",
).strip()
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv(
    "WEBPUSH_VAPID_PRIVATE_KEY",
    "",
).strip()
WEBPUSH_VAPID_SUBJECT = os.getenv(
    "WEBPUSH_VAPID_SUBJECT",
    "https://doblev3d.com.ar",
).strip()


# Internationalization

LANGUAGE_CODE = "es-ar"
TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_TZ = True
USE_I18N = True


# Static files

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# HTTPS / Railway

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

# En Railway son seguras por defecto. En runserver local quedan en HTTP,
# independientemente de DEBUG, para evitar redirecciones/cookies HTTPS
# incompatibles con el servidor de desarrollo.
SESSION_COOKIE_SECURE = _env_bool(
    "SESSION_COOKIE_SECURE",
    IS_RAILWAY,
)
CSRF_COOKIE_SECURE = _env_bool(
    "CSRF_COOKIE_SECURE",
    IS_RAILWAY,
)
SECURE_SSL_REDIRECT = _env_bool(
    "SECURE_SSL_REDIRECT",
    IS_RAILWAY,
)

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

CSRF_TRUSTED_ORIGINS = [
    "https://*.up.railway.app",
]

for origen in _env_list("CSRF_TRUSTED_ORIGINS"):
    if origen not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origen)

if railway_public_domain:
    railway_origin = f"https://{railway_public_domain}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)
