# Generated by Django 6.1.1 on 2026-09-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_remove_estadoimpresionpedido_estado_and_more'),
        ('productos', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('destino', models.CharField(choices=[('STOCK', 'Stock'), ('PEDIDO', 'Pedido')], default='STOCK', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('IMPRIMIENDO', 'Imprimiendo'), ('LISTO', 'Listo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('ingresado_stock', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='productos.producto')),
            ],
        ),
    ]
