# Generated by Django 6.1.1 on 2026-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='inicio_impresion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de impresión'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='tiempo_impresion_minutos',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiempo de impresión (minutos)'),
        ),
    ]
