# Generated manually for Doble V Bambu Bridge integration.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0003_impresora_alter_produccion_fecha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpresoraEstadoBambu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "nombre_bridge",
                    models.CharField(
                        blank=True,
                        max_length=100,
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        protocol="IPv4",
                    ),
                ),
                (
                    "conectada",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        max_length=50,
                    ),
                ),
                (
                    "progreso",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "minutos_restantes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "trabajo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "temperatura_nozzle",
                    models.FloatField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "temperatura_bed",
                    models.FloatField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "wifi",
                    models.CharField(
                        blank=True,
                        max_length=32,
                    ),
                ),
                (
                    "ultimo_evento_impresora",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "ultimo_contacto",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "impresora",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estado_bambu",
                        to="produccion.impresora",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "nombre_bridge",
                    "serial",
                ],
            },
        ),
    ]
