# Generated by Django 6.1.1 on 2026-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('KIT_SENSORIAL', 'Kit sensorial'), ('PRODUCTO', 'Producto'), ('OTRO', 'Otro')], max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('horas', models.PositiveIntegerField(default=0)),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('peso_gramos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje, por ejemplo 60 para 60%', max_digits=6)),
                ('requiere_impresion', models.BooleanField(default=True)),
                ('personalizable', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
