# Generated by Django 6.1.1 on 2026-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ejemplo: 60 para 60%', max_digits=6),
        ),
    ]
