# Generated by Django 6.1.1 on 2026-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_tipoproducto_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('PERSONALIZADO', 'Personalizado'), ('DESCARGADO', 'Descargado'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
