# Generated by Django 6.1.1 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0010_configuracioncatalogo_mensajes_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="catalogo_activo",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Si se desactiva, toda la tienda pública muestra una página de mantenimiento."
                ),
                verbose_name="Catálogo público activo",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="mensaje_mantenimiento",
            field=models.CharField(
                blank=True,
                default=(
                    "Estamos haciendo unos ajustes en la tienda. "
                    "Volvé a visitarnos en unos minutos."
                ),
                max_length=240,
                verbose_name="Mensaje de mantenimiento",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncatalogo",
            name="notificaciones_pedidos_web_activas",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Activa o desactiva globalmente los avisos push cuando entra una solicitud web."
                ),
                verbose_name="Notificaciones de pedidos web",
            ),
        ),
    ]
