plugins {
    id 'com.android.application'
}

android {
    namespace 'ar.com.doblev3d.gestion'
    compileSdk 35

    defaultConfig {
        applicationId "ar.com.doblev3d.gestion"
        minSdk 29
        targetSdk 35
        versionCode 3
        versionName "1.0.2"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
