import io
import tempfile
import zipfile

from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse

from produccion.models import Produccion

from .models import ArchivoImpresion, Producto, TipoProducto


class ArchivoImpresionTests(TestCase):
    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tempdir.cleanup)

        storage_override = self.override_settings(
            PRINT_FILES_ROOT=self.tempdir.name,
            PRINT_FILES_PERSISTENT=True,
            BAMBU_BRIDGE_TOKEN="test-bridge-token",
            STORAGES={
                "default": {
                    "BACKEND": "django.core.files.storage.FileSystemStorage",
                    "OPTIONS": {
                        "location": self.tempdir.name,
                        "base_url": "/_private_print_files/",
                    },
                },
                "staticfiles": {
                    "BACKEND": (
                        "django.contrib.staticfiles.storage.StaticFilesStorage"
                    ),
                },
            },
        )
        storage_override.enable()
        self.addCleanup(storage_override.disable)

        usuario = get_user_model().objects.create_user(
            username="gcode-test",
            password="test-pass",
        )
        self.client.force_login(usuario)

        tipo = TipoProducto.objects.create(
            nombre="Archivo impresión",
        )

        self.producto = Producto.objects.create(
            nombre="Pieza con G-code",
            categoria="PRODUCTO",
            tipo=tipo,
            horas=1,
            minutos=0,
            peso_gramos=10,
            margen_ganancia=50,
            requiere_impresion=True,
            stock=0,
            activo=True,
        )

    def _archivo_valido(self, nombre="pieza.gcode.3mf"):
        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                "; generated by Bambu Studio\nG28\n",
            )
            paquete.writestr(
                "Metadata/plate_1.json",
                "{}",
            )

        return SimpleUploadedFile(
            nombre,
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

    def test_subir_gcode_3mf_valido(self):
        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(),
                "nombre": "Perfil stock",
                "version": "v1",
                "perfil_impresora": "A1 · 0.4 mm",
                "cantidad_unidades": "6",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        registro = ArchivoImpresion.objects.get(
            producto=self.producto
        )

        self.assertEqual(
            registro.nombre,
            "Perfil stock",
        )
        self.assertEqual(
            registro.version,
            "v1",
        )
        self.assertEqual(
            registro.placas,
            [1],
        )
        self.assertEqual(
            registro.cantidad_unidades,
            6,
        )
        self.assertEqual(
            len(registro.sha256),
            64,
        )
        self.assertTrue(
            registro.predeterminado,
        )
        self.assertTrue(
            registro.archivo.storage.exists(
                registro.archivo.name
            )
        )

    def test_rechaza_archivo_que_no_es_3mf(self):
        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": SimpleUploadedFile(
                    "pieza.txt",
                    b"hola",
                    content_type="text/plain",
                ),
                "cantidad_unidades": "1",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )
        self.assertFalse(
            ArchivoImpresion.objects.exists()
        )

    def test_rechaza_mismo_archivo_duplicado(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(),
                "cantidad_unidades": "1",
            },
        )
        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "copia.gcode.3mf"
                ),
                "cantidad_unidades": "1",
            },
        )

        self.assertEqual(
            ArchivoImpresion.objects.count(),
            1,
        )

    def test_descarga_es_privada_y_entrega_archivo(self):
        self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(),
                "cantidad_unidades": "1",
            },
        )

        registro = ArchivoImpresion.objects.get()

        respuesta = self.client.get(
            reverse(
                "productos:archivo_impresion_descargar",
                args=[
                    self.producto.id,
                    registro.id,
                ],
            )
        )

        self.assertEqual(
            respuesta.status_code,
            200,
        )
        self.assertIn(
            "attachment",
            respuesta["Content-Disposition"],
        )


    def test_cada_cantidad_puede_tener_archivo_principal(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "x6.gcode.3mf"
                ),
                "cantidad_unidades": "6",
            },
        )

        archivo_6 = ArchivoImpresion.objects.get(
            cantidad_unidades=6
        )

        # Generamos otro contenido para evitar el control de duplicados.
        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                "; x12\nG28\nG1 X10\n",
            )

        archivo_12_upload = SimpleUploadedFile(
            "x12.gcode.3mf",
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

        self.client.post(
            url,
            {
                "archivo": archivo_12_upload,
                "cantidad_unidades": "12",
            },
        )

        archivo_12 = ArchivoImpresion.objects.get(
            cantidad_unidades=12
        )

        self.assertTrue(
            archivo_6.predeterminado
        )
        self.assertTrue(
            archivo_12.predeterminado
        )
        self.assertEqual(
            self.producto.archivo_impresion_para_cantidad(6).id,
            archivo_6.id,
        )
        self.assertEqual(
            self.producto.archivo_impresion_para_cantidad(12).id,
            archivo_12.id,
        )
        self.assertIsNone(
            self.producto.archivo_impresion_para_cantidad(3)
        )

    def test_subir_misma_cantidad_pide_confirmacion_y_reemplaza_principal(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "x4-v1.gcode.3mf"
                ),
                "cantidad_unidades": "4",
                "nombre": "X4 v1",
            },
        )

        primero = ArchivoImpresion.objects.get()

        def archivo_v2():
            buffer = io.BytesIO()
            with zipfile.ZipFile(
                buffer,
                "w",
                zipfile.ZIP_DEFLATED,
            ) as paquete:
                paquete.writestr(
                    "Metadata/plate_1.gcode",
                    "; alternativa v2\nG28\nG1 X31\n",
                )
            return SimpleUploadedFile(
                "x4-v2.gcode.3mf",
                buffer.getvalue(),
                content_type="application/octet-stream",
            )

        self.client.post(
            url,
            {
                "archivo": archivo_v2(),
                "cantidad_unidades": "4",
                "nombre": "X4 v2",
            },
        )

        self.assertEqual(
            ArchivoImpresion.objects.count(),
            1,
        )
        primero.refresh_from_db()
        self.assertTrue(
            primero.predeterminado
        )

        self.client.post(
            url,
            {
                "archivo": archivo_v2(),
                "cantidad_unidades": "4",
                "nombre": "X4 v2",
                "confirmar_reemplazo_principal": "1",
            },
        )

        self.assertEqual(
            ArchivoImpresion.objects.count(),
            2,
        )
        primero.refresh_from_db()
        segundo = ArchivoImpresion.objects.exclude(
            id=primero.id
        ).get()

        self.assertFalse(
            primero.predeterminado
        )
        self.assertTrue(
            segundo.predeterminado
        )
        self.assertEqual(
            self.producto.archivo_impresion_para_cantidad(4).id,
            segundo.id,
        )

    def test_sustituir_conserva_historial_y_misma_cantidad(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "pepino-x6-v1.gcode.3mf"
                ),
                "cantidad_unidades": "6",
                "nombre": "Pepino x6",
                "version": "v1",
            },
        )

        anterior = ArchivoImpresion.objects.get()

        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                "; version nueva\nG28\nG1 X20\n",
            )

        nuevo_upload = SimpleUploadedFile(
            "pepino-x6-v2.gcode.3mf",
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_reemplazar",
                args=[
                    self.producto.id,
                    anterior.id,
                ],
            ),
            {
                "archivo": nuevo_upload,
                "version": "v2",
                "notas": "Ajuste de soportes",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        anterior.refresh_from_db()
        nuevo = ArchivoImpresion.objects.exclude(
            id=anterior.id
        ).get()

        self.assertFalse(
            anterior.activo
        )
        self.assertFalse(
            anterior.predeterminado
        )
        self.assertTrue(
            nuevo.activo
        )
        self.assertTrue(
            nuevo.predeterminado
        )
        self.assertEqual(
            nuevo.cantidad_unidades,
            6,
        )
        self.assertEqual(
            nuevo.reemplaza_a_id,
            anterior.id,
        )
        self.assertEqual(
            nuevo.version,
            "v2",
        )


    def test_descarga_privada_para_raspberry_requiere_token(self):
        self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(),
                "cantidad_unidades": "1",
            },
        )

        registro = ArchivoImpresion.objects.get()

        url = reverse(
            "bambu_bridge_download_file",
            args=[registro.id],
        )

        # La Raspberry no tiene sesión de Gestión: autentica solo
        # mediante el Bearer token del bridge.
        self.client.logout()

        sin_token = self.client.get(url)

        self.assertEqual(
            sin_token.status_code,
            401,
        )

        con_token = self.client.get(
            url,
            HTTP_AUTHORIZATION=(
                "Bearer test-bridge-token"
            ),
        )

        self.assertEqual(
            con_token.status_code,
            200,
        )
        self.assertEqual(
            con_token["X-DV-SHA256"],
            registro.sha256,
        )
        self.assertEqual(
            con_token["X-DV-Quantity"],
            "1",
        )

    def test_sustituir_actualiza_producciones_pendientes(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "base.gcode.3mf"
                ),
                "cantidad_unidades": "6",
                "nombre": "Base x6",
                "version": "v1",
            },
        )

        anterior = ArchivoImpresion.objects.get()

        produccion = Produccion.objects.create(
            producto=self.producto,
            cantidad=6,
            destino="STOCK",
            estado="PENDIENTE",
            tiempo_impresion_minutos=60,
            archivo_impresion=anterior,
        )

        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                "; reemplazo\nG28\nG1 X42\n",
            )

        reemplazo = SimpleUploadedFile(
            "base-v2.gcode.3mf",
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

        self.client.post(
            reverse(
                "productos:archivo_impresion_reemplazar",
                args=[
                    self.producto.id,
                    anterior.id,
                ],
            ),
            {
                "archivo": reemplazo,
                "version": "v2",
            },
        )

        produccion.refresh_from_db()
        nuevo = ArchivoImpresion.objects.exclude(
            id=anterior.id
        ).get()

        self.assertEqual(
            produccion.archivo_impresion_id,
            nuevo.id,
        )


    def test_descarga_privada_por_produccion(self):
        self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(
                    "prod.gcode.3mf"
                ),
                "cantidad_unidades": "6",
            },
        )

        archivo = ArchivoImpresion.objects.get()

        produccion = Produccion.objects.create(
            producto=self.producto,
            cantidad=6,
            destino="STOCK",
            estado="PENDIENTE",
            tiempo_impresion_minutos=60,
            archivo_impresion=archivo,
        )

        self.client.logout()

        respuesta = self.client.get(
            reverse(
                "bambu_bridge_download_production_file",
                args=[produccion.id],
            ),
            HTTP_AUTHORIZATION=(
                "Bearer test-bridge-token"
            ),
        )

        self.assertEqual(
            respuesta.status_code,
            200,
        )
        self.assertEqual(
            respuesta["X-DV-Production-Code"],
            produccion.codigo,
        )
        self.assertEqual(
            respuesta["X-DV-SHA256"],
            archivo.sha256,
        )


    def test_sync_informa_archivos_pendientes_para_cache(self):
        self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(
                    "cache.gcode.3mf"
                ),
                "cantidad_unidades": "6",
            },
        )

        archivo = ArchivoImpresion.objects.get()

        produccion = Produccion.objects.create(
            producto=self.producto,
            cantidad=6,
            destino="STOCK",
            estado="PENDIENTE",
            tiempo_impresion_minutos=60,
            archivo_impresion=archivo,
        )

        respuesta = self.client.post(
            reverse("bambu_bridge_sync"),
            data='{"printers": []}',
            content_type="application/json",
            HTTP_AUTHORIZATION=(
                "Bearer test-bridge-token"
            ),
        )

        self.assertEqual(
            respuesta.status_code,
            200,
        )

        data = respuesta.json()

        self.assertEqual(
            len(data["files_to_cache"]),
            1,
        )
        item = data["files_to_cache"][0]

        self.assertEqual(
            item["production_id"],
            produccion.id,
        )
        self.assertEqual(
            item["file_id"],
            archivo.id,
        )
        self.assertEqual(
            item["sha256"],
            archivo.sha256,
        )
        self.assertTrue(
            item["download_path"].endswith(
                f"/{archivo.id}/download/"
            )
        )


    def test_reintento_repara_registro_sin_archivo_fisico(self):
        archivo_upload = self._archivo_valido(
            "pepino-x6.gcode.3mf"
        )

        contenido = archivo_upload.read()
        archivo_upload.seek(0)

        import hashlib

        sha = hashlib.sha256(
            contenido
        ).hexdigest()

        huerfano = ArchivoImpresion.objects.create(
            producto=self.producto,
            nombre="Pepino x6",
            version="v1",
            cantidad_unidades=6,
            archivo=(
                "productos/P0001/"
                "faltante.gcode.3mf"
            ),
            nombre_original=(
                "pepino-x6.gcode.3mf"
            ),
            tamano_bytes=len(contenido),
            sha256=sha,
            placas=[1],
            activo=True,
            predeterminado=True,
        )

        self.assertFalse(
            huerfano.archivo.storage.exists(
                huerfano.archivo.name
            )
        )

        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(
                    "pepino-x6.gcode.3mf"
                ),
                "cantidad_unidades": "6",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        huerfano.refresh_from_db()

        self.assertTrue(
            huerfano.archivo.storage.exists(
                huerfano.archivo.name
            )
        )
        self.assertEqual(
            ArchivoImpresion.objects.count(),
            1,
        )


    def test_subir_desde_producto_vincula_pendiente_de_misma_cantidad(self):
        produccion = Produccion.objects.create(
            producto=self.producto,
            cantidad=4,
            destino="STOCK",
            estado="PENDIENTE",
            tiempo_impresion_minutos=45,
        )

        self.assertIsNone(
            produccion.archivo_impresion_id
        )

        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(
                    "producto-x4.gcode.3mf"
                ),
                "cantidad_unidades": "4",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        archivo = ArchivoImpresion.objects.get(
            cantidad_unidades=4
        )

        produccion.refresh_from_db()

        self.assertEqual(
            produccion.archivo_impresion_id,
            archivo.id,
        )

    def test_cambiar_principal_actualiza_pendientes(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "x4-v1.gcode.3mf"
                ),
                "cantidad_unidades": "4",
                "nombre": "X4 v1",
            },
        )

        primero = ArchivoImpresion.objects.get()

        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                "; alternativa\nG28\nG1 X30\n",
            )

        segundo_upload = SimpleUploadedFile(
            "x4-v2.gcode.3mf",
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

        self.client.post(
            url,
            {
                "archivo": segundo_upload,
                "cantidad_unidades": "4",
                "nombre": "X4 v2",
                "confirmar_reemplazo_principal": "1",
            },
        )

        segundo = ArchivoImpresion.objects.exclude(
            id=primero.id
        ).get()

        produccion = Produccion.objects.create(
            producto=self.producto,
            cantidad=4,
            destino="STOCK",
            estado="PENDIENTE",
            tiempo_impresion_minutos=45,
            archivo_impresion=segundo,
        )

        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_predeterminar",
                args=[
                    self.producto.id,
                    primero.id,
                ],
            )
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        produccion.refresh_from_db()

        self.assertEqual(
            produccion.archivo_impresion_id,
            primero.id,
        )


    def test_extrae_peso_y_tiempo_desde_gcode_bambu(self):
        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                (
                    "; total filament weight [g] : 275.76\n"
                    "; model printing time: 14h 18m 30s; "
                    "total estimated time: 14h 24m 46s\n"
                    "G28\n"
                ),
            )

        archivo = SimpleUploadedFile(
            "pepino-x4.gcode.3mf",
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": archivo,
                "cantidad_unidades": "4",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        registro = ArchivoImpresion.objects.get(
            cantidad_unidades=4
        )

        self.assertEqual(
            str(registro.peso_estimado_gramos),
            "275.76",
        )
        self.assertEqual(
            registro.tiempo_estimado_minutos,
            865,
        )
        self.assertEqual(
            registro.peso_estimado_texto,
            "276 g",
        )
        self.assertEqual(
            registro.tiempo_estimado_texto,
            "14 h 25 min",
        )
