import io
import tempfile
import zipfile

from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse

from .models import ArchivoImpresion, Producto, TipoProducto


class ArchivoImpresionTests(TestCase):
    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tempdir.cleanup)

        storage_override = self.override_settings(
            PRINT_FILES_ROOT=self.tempdir.name,
            PRINT_FILES_PERSISTENT=True,
            STORAGES={
                "default": {
                    "BACKEND": "django.core.files.storage.FileSystemStorage",
                    "OPTIONS": {
                        "location": self.tempdir.name,
                        "base_url": "/_private_print_files/",
                    },
                },
                "staticfiles": {
                    "BACKEND": (
                        "django.contrib.staticfiles.storage.StaticFilesStorage"
                    ),
                },
            },
        )
        storage_override.enable()
        self.addCleanup(storage_override.disable)

        usuario = get_user_model().objects.create_user(
            username="gcode-test",
            password="test-pass",
        )
        self.client.force_login(usuario)

        tipo = TipoProducto.objects.create(
            nombre="Archivo impresión",
        )

        self.producto = Producto.objects.create(
            nombre="Pieza con G-code",
            categoria="PRODUCTO",
            tipo=tipo,
            horas=1,
            minutos=0,
            peso_gramos=10,
            margen_ganancia=50,
            requiere_impresion=True,
            stock=0,
            activo=True,
        )

    def _archivo_valido(self, nombre="pieza.gcode.3mf"):
        buffer = io.BytesIO()
        with zipfile.ZipFile(
            buffer,
            "w",
            zipfile.ZIP_DEFLATED,
        ) as paquete:
            paquete.writestr(
                "Metadata/plate_1.gcode",
                "; generated by Bambu Studio\nG28\n",
            )
            paquete.writestr(
                "Metadata/plate_1.json",
                "{}",
            )

        return SimpleUploadedFile(
            nombre,
            buffer.getvalue(),
            content_type="application/octet-stream",
        )

    def test_subir_gcode_3mf_valido(self):
        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(),
                "nombre": "Perfil stock",
                "version": "v1",
                "perfil_impresora": "A1 · 0.4 mm",
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )

        registro = ArchivoImpresion.objects.get(
            producto=self.producto
        )

        self.assertEqual(
            registro.nombre,
            "Perfil stock",
        )
        self.assertEqual(
            registro.version,
            "v1",
        )
        self.assertEqual(
            registro.placas,
            [1],
        )
        self.assertEqual(
            len(registro.sha256),
            64,
        )
        self.assertTrue(
            registro.predeterminado,
        )
        self.assertTrue(
            registro.archivo.storage.exists(
                registro.archivo.name
            )
        )

    def test_rechaza_archivo_que_no_es_3mf(self):
        respuesta = self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": SimpleUploadedFile(
                    "pieza.txt",
                    b"hola",
                    content_type="text/plain",
                ),
            },
        )

        self.assertEqual(
            respuesta.status_code,
            302,
        )
        self.assertFalse(
            ArchivoImpresion.objects.exists()
        )

    def test_rechaza_mismo_archivo_duplicado(self):
        url = reverse(
            "productos:archivo_impresion_subir",
            args=[self.producto.id],
        )

        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(),
            },
        )
        self.client.post(
            url,
            {
                "archivo": self._archivo_valido(
                    "copia.gcode.3mf"
                ),
            },
        )

        self.assertEqual(
            ArchivoImpresion.objects.count(),
            1,
        )

    def test_descarga_es_privada_y_entrega_archivo(self):
        self.client.post(
            reverse(
                "productos:archivo_impresion_subir",
                args=[self.producto.id],
            ),
            {
                "archivo": self._archivo_valido(),
            },
        )

        registro = ArchivoImpresion.objects.get()

        respuesta = self.client.get(
            reverse(
                "productos:archivo_impresion_descargar",
                args=[
                    self.producto.id,
                    registro.id,
                ],
            )
        )

        self.assertEqual(
            respuesta.status_code,
            200,
        )
        self.assertIn(
            "attachment",
            respuesta["Content-Disposition"],
        )
